<a href="https://colab.research.google.com/github/iams0rakim/studying/blob/main/DeepChem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --pre deepchem

     |████████████████████████████████| 609 kB 11.4 MB/s 


In [ ]:
import deepchem as dc
dc.__version__

'2.6.0.dev'

In [ ]:
!apt-get -qq install -y graphviz && pip install pydot
import pydot

In [ ]:
import deepchem as dc
import numpy as np

In [ ]:
x = np.random.random((4, 5))
y = np.random.random((4, 1))

In [ ]:
x

array([[0.04080952, 0.15392154, 0.78024459, 0.70485278, 0.60696447],
       [0.11108624, 0.73210795, 0.81447797, 0.47634287, 0.13768786],
       [0.60786458, 0.51694362, 0.96430954, 0.72999762, 0.82787107],
       [0.83692096, 0.31409974, 0.38939578, 0.69294929, 0.31594152]])

In [ ]:
dataset = dc.data.NumpyDataset(x, y)

In [ ]:
print(dataset.X)

[[0.04080952 0.15392154 0.78024459 0.70485278 0.60696447]
 [0.11108624 0.73210795 0.81447797 0.47634287 0.13768786]
 [0.60786458 0.51694362 0.96430954 0.72999762 0.82787107]
 [0.83692096 0.31409974 0.38939578 0.69294929 0.31594152]]


In [ ]:
np.array_equal(y, dataset.y)

True

In [ ]:
!pip install matplotlib-venn

In [ ]:
import deepchem as dc
dc.__version__

'2.6.0.dev'

In [ ]:
pip install rdkit-pypi

     |████████████████████████████████| 19.7 MB 87 kB/s 


# **predicting the solubility of small molecules given their chemical formulas (important property in drug development)**

In [ ]:
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='GraphConv')
train_dataset, valid_dataset, test_dataset = datasets

In [ ]:
model = dc.models.GraphConvModel(n_tasks=1, mode='regression', dropout=0.2)

In [ ]:
model.fit(train_dataset, nb_epoch=100)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/indexed_slices.py:449: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradient_tape/private__graph_conv_keras_model/graph_pool_1/Reshape_14:0", shape=(362,), dtype=int32), values=Tensor("gradient_tape/private__graph_conv_keras_model/graph_pool_1/Reshape_13:0", shape=(362, 64), dtype=float32), dense_shape=Tensor("gradient_tape/private__graph_conv_keras_model/graph_pool_1/Cast_4:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "shape. This may consume a large amount of memory." % value)
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/indexed_slices.py:449: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradient_tape/private__graph_conv_keras_model/graph_pool_1/Reshape_17:0", shape=(1076,), dtype=int32), values=Tensor("gradient_tape/private__graph_conv_keras_model/graph_pool_1/Reshape_16

0.10726743698120117

In [ ]:
metric = dc.metrics.Metric(dc.metrics.pearson_r2_score)
print("Training set score:", model.evaluate(train_dataset, [metric], transformers))
print("Test set score:", model.evaluate(test_dataset, [metric], transformers))

Training set score: {'pearson_r2_score': 0.9240049224326763}
Test set score: {'pearson_r2_score': 0.6791652542922814}


In [ ]:
solubilities = model.predict_on_batch(test_dataset.X[:10])
for molecule, solubility, test_solubility in zip(test_dataset.ids, solubilities, test_dataset.y):
    print(solubility, test_solubility, molecule)

[-1.5976019] [-1.60114461] c1cc2ccc3cccc4ccc(c1)c2c34
[0.8869097] [0.20848251] Cc1cc(=O)[nH]c(=S)[nH]1
[-1.1966829] [-0.01602738] Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 
[-1.7811105] [-2.82191713] c1ccc2c(c1)cc3ccc4cccc5ccc2c3c45
[-1.5775003] [-0.52891635] C1=Cc2cccc3cccc1c23
[1.7674952] [1.10168349] CC1CO1
[-0.42723668] [-0.88987406] CCN2c1ccccc1N(C)C(=S)c3cccnc23 
[-0.9313792] [-0.52649706] CC12CCC3C(CCc4cc(O)ccc34)C2CCC1=O
[-1.1108382] [-0.76358725] Cn2cc(c1ccccc1)c(=O)c(c2)c3cccc(c3)C(F)(F)F
[0.13319024] [-0.64020358] ClC(Cl)(Cl)C(NC=O)N1C=CN(C=C1)C(NC=O)C(Cl)(Cl)Cl 


In [ ]:
print(test_dataset)

<DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['c1cc2ccc3cccc4ccc(c1)c2c34' 'Cc1cc(=O)[nH]c(=S)[nH]1'
 'Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 ' ...
 'c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43' 'Cc1occc1C(=O)Nc2ccccc2'
 'OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O '], task_names: ['measured log solubility in mols per litre']>


In [ ]:
for X, y, w, id in test_dataset.itersamples():
  print(y, id)

[-1.60114461] c1cc2ccc3cccc4ccc(c1)c2c34
[0.20848251] Cc1cc(=O)[nH]c(=S)[nH]1
[-0.01602738] Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 
[-2.82191713] c1ccc2c(c1)cc3ccc4cccc5ccc2c3c45
[-0.52891635] C1=Cc2cccc3cccc1c23
[1.10168349] CC1CO1
[-0.88987406] CCN2c1ccccc1N(C)C(=S)c3cccnc23 
[-0.52649706] CC12CCC3C(CCc4cc(O)ccc34)C2CCC1=O
[-0.76358725] Cn2cc(c1ccccc1)c(=O)c(c2)c3cccc(c3)C(F)(F)F
[-0.64020358] ClC(Cl)(Cl)C(NC=O)N1C=CN(C=C1)C(NC=O)C(Cl)(Cl)Cl 
[-0.38569452] COc2c1occc1cc3ccc(=O)oc23 
[-0.62568785] CN2C(=C(O)c1ccccc1S2(=O)=O)C(=O)Nc3ccccn3 
[-0.39585553] Cc3cc2nc1c(=O)[nH]c(=O)nc1n(CC(O)C(O)C(O)CO)c2cc3C
[-2.05306753] c1ccc(cc1)c2ccc(cc2)c3ccccc3
[-0.29666474] CC34CC(=O)C1C(CCC2=CC(=O)CCC12C)C3CCC4(=O) 
[-0.73213651] c1ccc2c(c1)sc3ccccc23
[-1.27744393] CC23Cc1cnoc1C=C2CCC4C3CCC5(C)C4CCC5(O)C#C
[0.0081655] OC(C(=O)c1ccccc1)c2ccccc2
[0.97588054] OCC2OC(Oc1ccccc1CO)C(O)C(O)C2O
[-0.10796031] CC3C2CCC1(C)C=CC(=O)C(=C1C2OC3=O)C
[0.59847167] O=Cc2ccc1OCOc1c2 
[-0.60149498] CC1CCCCC1NC(=O)N

In [ ]:
print(y, id) #이렇게 하면 하나만 출력되니까 for문을 돌려야함 :)

[1.01458914] OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O 


In [ ]:
for X, y, w, ids in test_dataset.iterbatches(batch_size=50):
  print(y.shape)

(50, 1)
(50, 1)
(13, 1)


# **Creating Datasets**

In [ ]:
import numpy as np

X = np.random.random((10, 5))
y = np.random.random((10, 2))
dataset = dc.data.NumpyDataset(X=X, y=y)
print(dataset)

<NumpyDataset X.shape: (10, 5), y.shape: (10, 2), w.shape: (10, 1), ids: [0 1 2 3 4 5 6 7 8 9], task_names: [0 1]>


In [ ]:
dataset.to_dataframe()

X1        X2        X3        X4  ...        y1        y2    w  ids
0  0.651789  0.500985  0.129057  0.434669  ...  0.114869  0.706409  1.0    0
1  0.084574  0.581001  0.038852  0.317933  ...  0.087399  0.433153  1.0    1
2  0.491032  0.675981  0.145317  0.954887  ...  0.541805  0.574348  1.0    2
3  0.425356  0.510059  0.184388  0.981758  ...  0.934743  0.132796  1.0    3
4  0.402253  0.559620  0.917204  0.094059  ...  0.963304  0.410299  1.0    4
5  0.139989  0.578889  0.550969  0.067983  ...  0.367332  0.906457  1.0    5
6  0.854588  0.276907  0.038557  0.371790  ...  0.010884  0.496280  1.0    6
7  0.250594  0.255596  0.535847  0.053456  ...  0.829728  0.349046  1.0    7
8  0.822047  0.069210  0.131451  0.426764  ...  0.769784  0.590483  1.0    8
9  0.263408  0.478904  0.424562  0.291548  ...  0.169648  0.437793  1.0    9

[10 rows x 9 columns]

In [ ]:
import tempfile
with tempfile.TemporaryDirectory() as data_dir:
  disk_dataset = dc.data.DiskDataset.from_numpy(X=X, y=y, data_dir=data_dir)
  print(disk_dataset)

<DiskDataset X.shape: (10, 5), y.shape: (10, 2), w.shape: (10, 1), ids: [0 1 2 3 4 5 6 7 8 9], task_names: [0 1]>


In [ ]:
[method for method in dir(dc.molnet) if "load_" in method ]

['load_Platinum_Adsorption',
 'load_bace_classification',
 'load_bace_regression',
 'load_bandgap',
 'load_bbbc001',
 'load_bbbc002',
 'load_bbbp',
 'load_cell_counting',
 'load_chembl',
 'load_chembl25',
 'load_clearance',
 'load_clintox',
 'load_delaney',
 'load_factors',
 'load_freesolv',
 'load_function',
 'load_hiv',
 'load_hopv',
 'load_hppb',
 'load_kaggle',
 'load_kinase',
 'load_lipo',
 'load_mp_formation_energy',
 'load_mp_metallicity',
 'load_muv',
 'load_nci',
 'load_pcba',
 'load_pdbbind',
 'load_perovskite',
 'load_ppb',
 'load_qm7',
 'load_qm8',
 'load_qm9',
 'load_sampl',
 'load_sider',
 'load_sweet',
 'load_thermosol',
 'load_tox21',
 'load_toxcast',
 'load_uspto',
 'load_uv',
 'load_zinc15']

In [ ]:
len([method for method in dir(dc.molnet) if "load_" in method ])

42

# **MoleculeNet**

In [ ]:
tasks

['measured log solubility in mols per litre']

In [ ]:
datasets

(<DiskDataset X.shape: (902,), y.shape: (902, 1), w.shape: (902, 1), ids: ['CC(C)=CCCC(C)=CC(=O)' 'CCCC=C' 'CCCCCCCCCCCCCC' ...
  'Nc2cccc3nc1ccccc1cc23 ' 'C1CCCCCC1' 'OC1CCCCCC1'], task_names: ['measured log solubility in mols per litre']>,
 <DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['Nc1ncnc2nc[nH]c12 ' 'Nc1nc(O)nc2nc[nH]c12 '
  'Fc1cccc(F)c1C(=O)NC(=O)Nc2cc(Cl)c(F)c(Cl)c2F ' ...
  'OC(Cn1cncn1)(Cn2cncn2)c3ccc(F)cc3F '
  'FC(F)(F)c1cccc(c1)N2CC(CCl)C(Cl)C2=O' 'CC1(C)CON(Cc2ccccc2Cl)C1=O'], task_names: ['measured log solubility in mols per litre']>,
 <DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['c1cc2ccc3cccc4ccc(c1)c2c34' 'Cc1cc(=O)[nH]c(=S)[nH]1'
  'Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 ' ...
  'c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43' 'Cc1occc1C(=O)Nc2ccccc2'
  'OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O '], task_names: ['measured log solubility in mols per litre']>)

In [ ]:
train, valid, test = datasets

In [ ]:
train

<DiskDataset X.shape: (902,), y.shape: (902, 1), w.shape: (902, 1), ids: ['CC(C)=CCCC(C)=CC(=O)' 'CCCC=C' 'CCCCCCCCCCCCCC' ...
 'Nc2cccc3nc1ccccc1cc23 ' 'C1CCCCCC1' 'OC1CCCCCC1'], task_names: ['measured log solubility in mols per litre']>

In [ ]:
valid

<DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['Nc1ncnc2nc[nH]c12 ' 'Nc1nc(O)nc2nc[nH]c12 '
 'Fc1cccc(F)c1C(=O)NC(=O)Nc2cc(Cl)c(F)c(Cl)c2F ' ...
 'OC(Cn1cncn1)(Cn2cncn2)c3ccc(F)cc3F '
 'FC(F)(F)c1cccc(c1)N2CC(CCl)C(Cl)C2=O' 'CC1(C)CON(Cc2ccccc2Cl)C1=O'], task_names: ['measured log solubility in mols per litre']>

In [ ]:
test

<DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['c1cc2ccc3cccc4ccc(c1)c2c34' 'Cc1cc(=O)[nH]c(=S)[nH]1'
 'Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 ' ...
 'c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43' 'Cc1occc1C(=O)Nc2ccccc2'
 'OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O '], task_names: ['measured log solubility in mols per litre']>

In [ ]:
train.X[0]

In [ ]:
transformers

In [ ]:
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer="ECFP", splitter="scaffold")

In [ ]:
(train, valid, test) = datasets

In [ ]:
train

<DiskDataset X.shape: (902, 1024), y.shape: (902, 1), w.shape: (902, 1), ids: ['CC(C)=CCCC(C)=CC(=O)' 'CCCC=C' 'CCCCCCCCCCCCCC' ...
 'Nc2cccc3nc1ccccc1cc23 ' 'C1CCCCCC1' 'OC1CCCCCC1'], task_names: ['measured log solubility in mols per litre']>

In [ ]:
train.X[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
import deepchem as dp
import numpy as np

In [ ]:
x = np.random.random((4, 5))
y = np.random.random((4, 1))

In [ ]:
x

array([[0.57216657, 0.50576806, 0.66252111, 0.53599464, 0.19204482],
       [0.38571697, 0.45989269, 0.08348221, 0.83393047, 0.61552424],
       [0.32564672, 0.85446369, 0.61780513, 0.47630403, 0.31285117],
       [0.58280655, 0.53701563, 0.20483664, 0.742015  , 0.91662074]])

In [ ]:
dataset = dc.data.NumpyDataset(x, y)

In [ ]:
print(dataset.X)

[[0.57216657 0.50576806 0.66252111 0.53599464 0.19204482]
 [0.38571697 0.45989269 0.08348221 0.83393047 0.61552424]
 [0.32564672 0.85446369 0.61780513 0.47630403 0.31285117]
 [0.58280655 0.53701563 0.20483664 0.742015   0.91662074]]


In [ ]:
print(dataset.y)

[[0.58655306]
 [0.64357696]
 [0.28027519]
 [0.74431899]]


In [ ]:
np.array_equal(x, dataset.X)

True

In [ ]:
np.array_equal(y, dataset.y)

True

In [ ]:
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()

In [ ]:
tox21_tasks

['NR-AR',
 'NR-AR-LBD',
 'NR-AhR',
 'NR-Aromatase',
 'NR-ER',
 'NR-ER-LBD',
 'NR-PPAR-gamma',
 'SR-ARE',
 'SR-ATAD5',
 'SR-HSE',
 'SR-MMP',
 'SR-p53']

In [ ]:
len(tox21_tasks)

12

In [ ]:
tox21_datasets

(<DiskDataset X.shape: (6264, 1024), y.shape: (6264, 12), w.shape: (6264, 12), task_names: ['NR-AR' 'NR-AR-LBD' 'NR-AhR' ... 'SR-HSE' 'SR-MMP' 'SR-p53']>,
 <DiskDataset X.shape: (783, 1024), y.shape: (783, 12), w.shape: (783, 12), ids: ['N#C[C@@H]1CC(F)(F)CN1C(=O)CNC1CC2CCC(C1)N2c1ncccn1'
  'CN(C)C(=O)NC1(c2ccccc2)CCN(CCC[C@@]2(c3ccc(Cl)c(Cl)c3)CCCN(C(=O)c3ccccc3)C2)CC1'
  'CSc1nnc(C(C)(C)C)c(=O)n1N' ...
  'O=C(O[C@H]1CN2CCC1CC2)N1CCc2ccccc2[C@@H]1c1ccccc1'
  'C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@@H]4[C@H]3C(=C)C[C@@]21CC'
  'NC(=O)C(c1ccccc1)(c1ccccc1)[C@@H]1CCN(CCc2ccc3c(c2)CCO3)C1'], task_names: ['NR-AR' 'NR-AR-LBD' 'NR-AhR' ... 'SR-HSE' 'SR-MMP' 'SR-p53']>,
 <DiskDataset X.shape: (784, 1024), y.shape: (784, 12), w.shape: (784, 12), ids: ['CC1(C)S[C@@H]2[C@H](NC(=O)Cc3ccccc3)C(=O)N2[C@H]1C(=O)O.CC1(C)S[C@@H]2[C@H](NC(=O)Cc3ccccc3)C(=O)N2[C@H]1C(=O)O.c1ccc(CNCCNCc2ccccc2)cc1'
  'CC(C)(c1ccc(Oc2ccc3c(c2)C(=O)OC3=O)cc1)c1ccc(Oc2ccc3c(c2)C(=O)OC3=O)cc1'
  'Cc1cc(C(C)(C)C)c(O)c(C)c1

In [ ]:
train_dataset, valid_dataset, test_dataset = tox21_datasets

In [ ]:
train_dataset.X.shape

(6264, 1024)

In [ ]:
valid_dataset.X.shape

(783, 1024)

In [ ]:
test_dataset.X.shape

(784, 1024)

In [ ]:
np.shape(train_dataset.y)

(6264, 12)

In [ ]:
np.shape(valid_dataset.y)

(783, 12)

In [ ]:
np.shape(test_dataset.y)

(784, 12)